Feedback
pykili/py-204-hw1-zadushevno pull request #1
Opened 2020-10-15 20:34 UTC by Sapunov

:wave:! GitHub Classroom created this pull request as a place for your teacher to leave feedback on your work. It will update automatically. **Don’t close or merge this pull request**, unless you’re instructed to do so by your teacher.

In this pull request, your teacher can leave comments and feedback on your code. Click the **Subscribe** button to be notified if that happens.

Click the **Files changed** or **Commits** tab to see all of the changes pushed to `master` since the assignment started. Your teacher can see this too.

<details>
<summary>
<strong>Notes for teachers</strong>
</summary>

Use this PR to leave feedback. Here are some tips:

- Click the **Files changed** tab to see all of the changes pushed to `master` since the assignment started. To leave comments on specific lines of code, put your cursor over a line of code and click the blue **+** (plus sign). To learn more about comments, read “[Commenting on a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request)”.
- Click the **Commits** tab to see the commits pushed to `master`. Click a commit to see specific changes.
- If you turned on autograding, then click the **Checks** tab to see the results.
- This page is an overview. It shows commits, line comments, and general comments. You can leave a general comment below.

For more information about this pull request, read “[Leaving assignment feedback in GitHub](https://classroom.github.com/help/leaving-feedback-in-github)”.
</details>

2020-10-24 15:16 UTC, oserikov reviewed
всё ок, но пожалусто замените некоторые вызовы классных методов самостоятельной их реализацией (подробнее в комментах)

2020-10-24 15:16 UTC, oserikov commented on task_6/solution_6.py
> +        print(j+1, sep='', end='')
Советую решать задачу без `sep`-ов и `end`-ов, более-менее опираясь на программу первых двух пар. Эта задача не про владение выразительным питоном, а про придумать простенький алгоритм при помощи минимальных инструментов

2020-10-24 15:16 UTC, oserikov commented on task_4/solution_4_1.py
> +            f2 = user_input.find('\t', f1+1, len(user_input)-1)
Советую решить задачу без использования метода `файнд`. Он и правда классный, но есть отдельный челлендж в том, чтобы уметь реализовать простой алгоритм, опираясь на самую-самую базу. (может, на собеседовании пригодится, а может -- в другом ЯП, методы которого вам будут вновинку)

2020-10-24 15:16 UTC, oserikov commented on task_4/solution_4_1.py
> +            f2 = user_input.find('\t', f1+1, len(user_input)-1)
Если лениво всё это править, запрогайте в качестве упражнения файнд где-то отдельно маленькой программой: нужно считать два слова, найти позицию одного в другом, напечатать.

2020-10-24 15:16 UTC, oserikov commented on task_2/solution_2.py
> +    if user_input.count(i) > user_input.count(most_frequent_character):
Советую решить задачу без `каунт`. Упражнение именно в том, чтобы запрогать простой алгоритм минимальными средствами. В жизни это пригождается редко, но пригождается (иногда память на красивые методы подводит и смекалка -- единственное спасение).

2020-10-24 15:16 UTC, oserikov commented on task_2/solution_2.py
> +    if user_input.count(i) > user_input.count(most_frequent_character):
Если лениво всё править, запрогайте отдельно маленькую программу, которая спросит слово и символ и скажет сколько раз символ есть в слове.

2020-10-24 15:18 UTC, oserikov requested changes
запрашиваю доработку

2020-11-16 22:30 UTC, merged

2020-11-18 10:46 UTC, DariaRev commented
Оценка - 10
5 - что такое front_vow?
8 - неправильно считает среднее, если пользователь не ввел 0, программа все равно считает среднее